# Generated by Django 4.0.4 on 2022-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_dev_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('acc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Force_Torque_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_torque_dev_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('force', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sound_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_dev_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('freq', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rin', models.IntegerField()),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('temp_dev_id', models.IntegerField()),
                ('acc_dev_id', models.IntegerField()),
                ('force_torque_dev_id', models.IntegerField()),
                ('sound_dev_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_dev_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('body_temp', models.FloatField()),
                ('amb_temp', models.FloatField()),
            ],
        ),
    ]
